# Generated by Django 4.2.13 on 2024-05-18 17:21
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id', models.CharField(
                        max_length=255,
                        primary_key=True, serialize=False,
                    ),
                ),
                ('send_id', models.CharField(max_length=255)),
                ('balance', models.BigIntegerField()),
                ('credit_limit', models.BigIntegerField()),
                ('account_type', models.CharField(max_length=255)),
                ('currency_code', models.IntegerField()),
                (
                    'cashback_type', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='ClientInfo',
            fields=[
                (
                    'client_id', models.CharField(
                        max_length=255, primary_key=True, serialize=False,
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'client_info',
            },
        ),
        migrations.CreateModel(
            name='StatementItem',
            fields=[
                (
                    'id', models.CharField(
                        max_length=255,
                        primary_key=True, serialize=False,
                    ),
                ),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('mcc', models.IntegerField()),
                ('original_mcc', models.IntegerField()),
                ('hold', models.BooleanField()),
                ('amount', models.BigIntegerField()),
                ('operation_amount', models.BigIntegerField()),
                ('currency_code', models.IntegerField()),
                ('commission_rate', models.BigIntegerField()),
                ('cashback_amount', models.BigIntegerField()),
                ('balance', models.BigIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                (
                    'receipt_id', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                (
                    'invoice_id', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                (
                    'counter_edrpou', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                (
                    'counter_iban', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                (
                    'counter_name', models.CharField(
                        blank=True, max_length=255, null=True,
                    ),
                ),
                (
                    'account', models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='statement_items', to='main.account',
                    ),
                ),
            ],
            options={
                'db_table': 'statement_items',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='client',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='accounts', to='main.clientinfo',
            ),
        ),
    ]
