# Generated by Django 4.2.13 on 2024-05-18 18:57
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategoryCode',
            fields=[
                ('code', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('of_interest', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.AlterModelOptions(
            name='clientinfo',
            options={
                'verbose_name': 'Client Info',
                'verbose_name_plural': 'Client Info',
            },
        ),
        migrations.AlterModelOptions(
            name='statementitem',
            options={
                'verbose_name': 'Statement Item',
                'verbose_name_plural': 'Statement Items',
            },
        ),
    ]
