# Generated by Django 4.2.13 on 2024-05-19 18:12
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_merchantcategorycode_alter_account_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetingConfig',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True, serialize=False, verbose_name='ID',
                    ),
                ),
                (
                    'daily_allowance', models.IntegerField(
                        help_text='Daily spending limit in integer value',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Budgeting Config',
                'verbose_name_plural': 'Budgeting Config',
                'db_table': 'single_budgeting_config',
            },
        ),
        migrations.AlterModelOptions(
            name='merchantcategorycode',
            options={
                'verbose_name': 'Merchant Category Code',
                'verbose_name_plural': 'Merchant Category Codes',
            },
        ),
    ]
