# Generated by Django 4.2.13 on 2024-05-19 21:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_budgetingconfig_alter_merchantcategorycode_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetingconfig',
            name='budgeting_start_day',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='budgetingconfig',
            name='daily_allowance',
            field=models.IntegerField(
                default=100000, help_text='Daily spending limit in integer value',
            ),
        ),
    ]
